<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>OSSStudio</RootNamespace>
    <AssemblyName>OSS-Studio</AssemblyName>
    <ApplicationIcon>Assets\OSS-Studio.ico</ApplicationIcon>
    <MewUIBackend>Direct2D</MewUIBackend>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AlibabaCloud.OSS.V2" Version="0.2.0" />
    <PackageReference Include="Aprillz.MewUI.Windows" Version="0.19.1" />
    <TrimmerRootAssembly Include="AlibabaCloud.OSS.V2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="artifacts\**\*.cs" />
    <Compile Remove="Inspection\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\OSS-Studio.ico" />
    <EmbeddedResource Include="Assets\OSS-Studio.png" />
  </ItemGroup>
</Project>
