<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>OSSClient</RootNamespace>
    <AssemblyName>OSSClient</AssemblyName>
    <MewUIBackend>Direct2D</MewUIBackend>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aprillz.MewUI.Windows" Version="0.19.1" />
  </ItemGroup>
</Project>
